---
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  name: example-plan
  namespace: konveyor-forklift
spec:
  provider:
    source:
      namespace: ''
      name: ''
    destination:
      namespace: ''
      name: ''

