---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: konveyor-forklift
spec:
  feature_ui: 'true'
  feature_validation: 'true'
  feature_must_gather_api: 'true'
